language: node_js
node_js:
  - "16"

if: branch IN (prepro, master)

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

install:
  - npm install

jobs:
  include:
    - stage: Unit tests
      if: branch = prepro
      script: npm run test -- --no-watch --no-progress
    - stage: Deploy to heroku prepro
      if: branch = prepro
      script: ignore
      deploy: &heroku
        provider: heroku
        api_key: $HEROKU_AUTH_TOKEN
        app: tablab-app-prepro
        on:
          prepro
    - stage: Deploy to heroku prod
      if: branch = master
      script: ignore
      deploy: &heroku
        provider: heroku
        api_key: $HEROKU_AUTH_TOKEN
        app: tablab-app
        on:
          master