language: node_js
node_js:
  - "16"

if: branch = test
addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

install:
  - npm install

jobs:
  include:
    - stage: unit tests
      script: npm run test -- --no-watch --no-progress
    - stage: deploy to heroku
        script: skip
        deploy: &heroku
          provider: heroku
          app: tablab-app
          api_key: $HEROKU_AUTH_TOKEN